from .standard import *

CONSTANT_GATES = [OFF, ON]
BASIC_GATES = [NOT, AND, OR, XOR]
EXTENDED_GATES = [NAND, NOR, XNOR]
THREE_INPUT_GATES = [AND3, OR3, NAND3, NOR3, XOR3, XNOR3, MAJ3]

MINIMAL_SET = [NAND]
STANDARD_SET = [NOT, AND, OR]
EXTENDED_SET = [NOT, AND, OR, XOR, NAND, NOR]
COMPLETE_SET = [NOT, AND, OR, XOR, NAND, NOR, XNOR, AND3, OR3, NAND3, NOR3, XOR3, XNOR3, MAJ3]
ALL_GATES = [OFF, ON, NOT, AND, OR, XOR, NAND, NOR, XNOR, AND3, OR3, NAND3, NOR3, XOR3, XNOR3, MAJ3]

__all__ = [
    "OFF", "ON", "NOT", "AND", "OR", "XOR", "NAND", "NOR", "XNOR",
    "AND3", "OR3", "NAND3", "NOR3", "XOR3", "XNOR3", "MAJ3",
    "CONSTANT_GATES", "BASIC_GATES", "EXTENDED_GATES", "THREE_INPUT_GATES",
    "MINIMAL_SET", "STANDARD_SET", "EXTENDED_SET", "COMPLETE_SET", "ALL_GATES"
]
